config/routes.rb
Rails.application.routes.draw do
  resources :funs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fun.rb
class Fun < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/funs_controller.rb
class FunsController < ApplicationController
  before_action :set_fun, only: [:show, :edit, :update, :destroy]

  # GET /funs
  # GET /funs.json
  def index
    @funs = Fun.all
  end

  # GET /funs/1
  # GET /funs/1.json
  def show
  end

  # GET /funs/new
  def new
    @fun = Fun.new
  end

  # GET /funs/1/edit
  def edit
  end

  # POST /funs
  # POST /funs.json
  def create
    @fun = Fun.new(fun_params)

    respond_to do |format|
      if @fun.save
        format.html { redirect_to @fun, notice: 'Fun was successfully created.' }
        format.json { render :show, status: :created, location: @fun }
      else
        format.html { render :new }
        format.json { render json: @fun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funs/1
  # PATCH/PUT /funs/1.json
  def update
    respond_to do |format|
      if @fun.update(fun_params)
        format.html { redirect_to @fun, notice: 'Fun was successfully updated.' }
        format.json { render :show, status: :ok, location: @fun }
      else
        format.html { render :edit }
        format.json { render json: @fun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funs/1
  # DELETE /funs/1.json
  def destroy
    @fun.destroy
    respond_to do |format|
      format.html { redirect_to funs_url, notice: 'Fun was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fun
      @fun = Fun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fun_params
      params.require(:fun).permit(:item)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funs_helper.rb
module FunsHelper
end

app/views/funs/_form.html.erb
<%= form_with(model: fun, local: true) do |form| %>
  <% if fun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fun.errors.count, "error") %> prohibited this fun from being saved:</h2>

      <ul>
      <% fun.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item, id: :fun_item %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funs/edit.html.erb
<h1>Editing Fun</h1>

<%= render 'form', fun: @fun %>

<%= link_to 'Show', @fun %> |
<%= link_to 'Back', funs_path %>

app/views/funs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funs</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funs.each do |fun| %>
      <tr>
        <td><%= fun.item %></td>
        <td><%= link_to 'Show', fun %></td>
        <td><%= link_to 'Edit', edit_fun_path(fun) %></td>
        <td><%= link_to 'Destroy', fun, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fun', new_fun_path %>

app/views/funs/new.html.erb
<h1>New Fun</h1>

<%= render 'form', fun: @fun %>

<%= link_to 'Back', funs_path %>

app/views/funs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @fun.item %>
</p>

<%= link_to 'Edit', edit_fun_path(@fun) %> |
<%= link_to 'Back', funs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleOnline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>